spring:
  datasource:
    url: jdbc:mysql://192.168.1.106:3306/db_stu?serverTimezone=GMT%2B8
    username: ljc
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
dubbo:
  registry:
    address: zookeeper://120.77.153.175:2181
  application:
    name: stuprovidercls
  protocol:
    port: -1
  consumer:
    check: false
