spring:
  datasource:
    url: jdbc:mysql://10.36.140.200/db_stu?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
dubbo:
  registry:
#    address: zookeeper://192.168.79.188:2181
    address: zookeeper://120.77.153.175:2181
  application:
    name: stuprovidercls
  protocol:
    port: -1
  consumer:
    check: false
