spring:
  datasource:
    url: jdbc:mysql:///db_tea?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
dubbo:
  registry:
    address: zookeeper://120.77.153.175:2181
  application:
    name: teaprovider
  protocol:
    port: -1
  consumer:
    check: false
