spring:
  datasource:
    url: jdbc:mysql://120.77.153.175:3306/db_cls?serverTimezone=GMT%2B8
    username: root1
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
dubbo:
  registry:
    address: zookeeper://120.77.153.175:2181
  application:
    name: clsprovider
  protocol:
    port: -1
  consumer:
    check: false
