spring:
  datasource:
    url: jdbc:mysql:///db_cls?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
dubbo:
  registry:
    address: zookeeper://192.168.239.200:2181
  application:
    name: clsprovider
  protocol:
    port: -1
  consumer:
    check: false
